# Generated by Django 4.0.5 on 2022-06-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_news', models.DateField()),
                ('viwes_news', models.CharField(max_length=100)),
                ('txt_news', models.CharField(max_length=400)),
            ],
        ),
    ]
