# Generated by Django 4.0.4 on 2022-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(null=True, upload_to='courseimage/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='timeperiod',
            field=models.IntegerField(null=True, verbose_name='مدت آموزش (ساعت)'),
        ),
    ]
